# Generated by Django 3.1.7 on 2021-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='danger_weight',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='ip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.TextField(blank=True),
        ),
    ]
