# Generated by Django 3.1.7 on 2021-03-01 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('complaint_face_picture', models.ImageField(blank=True, null=True, upload_to='complaints/pictures')),
                ('category', models.CharField(choices=[('0.1', 'No mask'), ('0.5', 'No mask + Symptomatic'), ('0.9', 'No mask + Symptomatic + Unhygienic')], max_length=30)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'complaint_face_picture')},
            },
        ),
    ]
